#ifndef	MCCULLABLE_CULLABLEDEF_H
#define	MCCULLABLE_CULLABLEDEF_H

enum	mcCullableClassOrder
{
	SKYHAT_PRIORITY,
	INST_CITY_MODELS_PRIORITY,
	CITY_MODELS_PRIORITY,
	PROPS_PRIORITY,
	AMBIENT_TRAFFIC_PRIORITY,
	TRAINS_PRIORITY,
	TRAFFIC_LIGHTS_PRIORITY,
	PEDS_PRIORITY,
	CARS_PRIORITY,
	RM_CARS_PRIORITY,

	MOTION_BLUR_PRIORITY,

	PARTICLE_FOG_PRIORITY,
	GLOWS_PRIORITY,

	CULLABLE_CLASS_ORDER_MAX
};

enum	mcPassTypes
{
	dtCULLING				= 0x0001,
	dtREFLECTING_GROUND		= 0x0002,
	dtREFLECTED_OBJECTS		= 0x0004,
	dtMAIN_SHADOWED			= 0x0008,
	dtSHADOWS				= 0x0010,
	dtMAIN_UNSHADOWED		= 0x0020,
	dtPLAYER_VEHICLE		= 0x0040,
	dtLIGHT_GLOWS			= 0x0080,
	dtPTX_SYSTEMS			= 0x0100,
	dtHEADLIGHT_CONE		= 0x0200,
	dtALPHA					= 0x0400,
	dtEND					= 0x0800
};

#endif
